In [1]:
x=int(input("Enter a Number:"))
y=int(input("Enter second number:"))
if(x==45):
            print("Its 45")
else:
            print(x+y)
            
            
            

Enter a Number:45
Enter second number:45
Its 45


In [4]:
x=10



In [5]:
type(x)

int

int

In [7]:
p=[10,12,14,16,18]
p

    


[10, 12, 14, 16, 18]

In [8]:
p.insert(2,25)

In [9]:
p

[10, 12, 25, 14, 16, 18]

In [10]:
y=[10,2,3,4,5,6,[4,5,6,],7]

In [11]:
y

[10, 2, 3, 4, 5, 6, [4, 5, 6], 7]

In [12]:
d2={12:"hello",(1,2,3,4):[4,5,6,7]}

In [13]:
d2[12]

'hello'

In [15]:
x=input("Enter the User Name:")
y=input("Enter the Password:")
if(x=="Mayank") and (y=="Hi"):
  print('Welcome')
else:
    print("Try Again")

Enter the User Name:Mayank
Enter the Password:Mayank
Try Again


In [16]:
x=input("Enter the User Name:")

if(x=="Mayank"):
  y=input("Enter the Password:")
if(y=="Mayank"):
  print("Welcome")
else:
  print("Try Again")  

Enter the User Name:Mayank
Enter the Password:Mayank
Welcome


In [17]:
for i in range(10):
 print(i)


0
1
2
3
4
5
6
7
8
9


In [18]:
for i in range(1,10,2):
  print(i)
  

1
3
5
7
9


In [19]:
l=['Mayank','Dikshant','[Yash']
for i in range(len(l)):
  print(i)
  

0
1
2


In [24]:
 s=[]
 l=['Mayank','Dikshant','[Yash']
 for i in l:
  print(str(len(i)),":",i)
  s.append(len(i))
  print(s)


6 : Mayank
[6]
8 : Dikshant
[6, 8]
5 : [Yash
[6, 8, 5]


In [26]:
def name():
  print('Mayank')
  

In [27]:
name()

Mayank


In [28]:
def name(x):
  print('Mayank and',x)

name('Dikshant')
name('Yash')


Mayank and Dikshant
Mayank and Yash


In [29]:
import numpy as np


In [31]:
x=np.array([10,11,12,13])
print(x)



[10 11 12 13]


In [32]:
x=np.array([[10,11,12,13],[14,15,16,17]])
print(x)


[[10 11 12 13]
 [14 15 16 17]]


In [33]:
print(x.ndim)


2


In [34]:
x=np.array([[10,11,12,13],[14,15,16,17]])
print(x.ndim)

2


In [35]:
print(x)
print(x.sum())
print(x.min())
print(x.min())
print(x.argmax())
print(x.argmin())

[[10 11 12 13]
 [14 15 16 17]]
108
10
10
7
0


In [36]:
x[0,0]

10

In [37]:
y=x[:,-1:]


In [38]:
y

array([[13],
       [17]])

In [40]:
x.shape

(2, 4)

In [42]:
b=x.reshape(4,2)

In [43]:
x.transpose()

array([[10, 14],
       [11, 15],
       [12, 16],
       [13, 17]])

In [44]:
a=0
a=np.arange(16).reshape(4,4)


In [45]:
a[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a = np.arange(18).reshape(3,3,2)                        

In [55]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])